import "../styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { twMerge } from "tailwind-merge";
import Navigation from "@/components/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="w-full h-full font-sans">
      <body
        className={twMerge(
          inter.className,
          "bg-white dark:bg-black dark:text-white relative"
        )}
      >
        <Navigation />
        {children}
      </body>
    </html>
  );
}
